# Generated by Django 2.2.28 on 2025-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15)),
                ('prodact_or_group', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=40)),
                ('operation_number', models.IntegerField()),
                ('size', models.CharField(max_length=15)),
                ('slash_time', models.IntegerField()),
                ('slash_prodaction_date', models.DateField()),
                ('cut_time', models.IntegerField()),
                ('cut_prodaction_date', models.DateField()),
                ('cut_work_shift', models.IntegerField()),
                ('comment', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15)),
                ('statys', models.CharField(max_length=15)),
                ('date_add', models.DateTimeField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prodact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=15)),
                ('number_in_order_list', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('factory_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('kategory', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=40)),
            ],
        ),
    ]
