# Generated by Django 5.2.5 on 2025-08-28 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodact',
            name='number',
        ),
        migrations.AddField(
            model_name='prodact',
            name='number_in_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Number in Order title'),
        ),
        migrations.AlterField(
            model_name='cutoperation',
            name='cut_work_shift',
            field=models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 16, 9, 26, 813526), verbose_name='Date add title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.date(2025, 8, 28), verbose_name='Date end title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.date(2025, 8, 28), verbose_name='Date start title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=9, verbose_name='Order number title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statys',
            field=models.CharField(choices=[('Prodaction', 'Prodaction'), ('Pause', 'Pause'), ('Closed', 'Closed'), ('Deleted', 'Deleted')], default='Pause', max_length=15, verbose_name='Statys title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='factory_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Factory number title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='kategory',
            field=models.CharField(choices=[('Ventilator', 'Ventilator'), ('Zernoprovod', 'Zernoprovod'), ('Zernosushilka', 'Zernosushilka'), ('Over', 'Over')], default='Over', max_length=20, verbose_name='Kategory title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Prodact name title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='order_number',
            field=models.CharField(max_length=9, verbose_name='Order number title'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='specification',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Specification title'),
        ),
    ]
