# Generated by Django 2.2.28 on 2025-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodaction_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(),
        ),
    ]
