# Generated by Django 5.2.5 on 2025-08-29 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersList', '0002_remove_prodact_number_prodact_number_in_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 29, 13, 3, 22, 201844), verbose_name='Date add title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.date(2025, 8, 29), verbose_name='Date end title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.date(2025, 8, 29), verbose_name='Date start title'),
        ),
    ]
