# Generated by Django 5.2.5 on 2025-08-31 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersList', '0004_alter_order_date_add_alter_order_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 31, 11, 23, 54, 994834, tzinfo=datetime.timezone.utc), verbose_name='Date add title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 8, 31, 11, 23, 54, 994879, tzinfo=datetime.timezone.utc), verbose_name='Date end title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2025, 8, 31, 11, 23, 54, 994864, tzinfo=datetime.timezone.utc), verbose_name='Date start title'),
        ),
    ]
