# Generated by Django 5.2.5 on 2025-09-24 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersList', '0005_alter_order_date_add_alter_order_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 13, 43, 45, 319248), verbose_name='Date add title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 13, 43, 45, 319294), verbose_name='Date end title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2025, 9, 24, 13, 43, 45, 319281), verbose_name='Date start title'),
        ),
    ]
