# Generated by Django 5.2.5 on 2025-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('grave', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=30)),
                ('marshrut', models.CharField(max_length=60)),
                ('poddon', models.CharField(max_length=15)),
                ('comment', models.TextField()),
                ('actual_date', models.DateTimeField()),
                ('frw_file_name', models.FileField(upload_to='')),
                ('frw_file_folder', models.TextField()),
                ('frw_file_date', models.DateTimeField()),
                ('frw_file_parts', models.TextField()),
                ('frw_valid', models.SmallIntegerField()),
                ('cdw_file_name', models.FileField(upload_to='')),
                ('cdw_file_folder', models.TextField()),
                ('cdw_file_date', models.DateTimeField()),
                ('cdw_valid', models.SmallIntegerField()),
                ('stage1', models.CharField(max_length=30)),
                ('time1', models.FloatField()),
                ('description1', models.TextField()),
                ('stage2', models.CharField(max_length=30)),
                ('time2', models.FloatField()),
                ('description2', models.TextField()),
                ('stage3', models.CharField(max_length=30)),
                ('time3', models.FloatField()),
                ('description3', models.TextField()),
                ('stage4', models.CharField(max_length=30)),
                ('time4', models.FloatField()),
                ('description4', models.TextField()),
                ('stage5', models.CharField(max_length=30)),
                ('time5', models.FloatField()),
                ('description5', models.TextField()),
                ('stage6', models.CharField(max_length=30)),
                ('time6', models.FloatField()),
                ('description6', models.TextField()),
                ('stage7', models.CharField(max_length=30)),
                ('time7', models.FloatField()),
                ('description7', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('thickness', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('variant1', models.CharField(max_length=70)),
                ('variant2', models.CharField(max_length=70)),
                ('variant3', models.CharField(max_length=70)),
                ('variant4', models.CharField(max_length=70)),
                ('variant5', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('composition', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('actual_date', models.DateTimeField()),
                ('cdw_file_name', models.FileField(upload_to='')),
                ('cdw_file_folder', models.TextField()),
                ('cdw_file_date', models.DateTimeField()),
                ('cdw_valid', models.SmallIntegerField()),
            ],
        ),
    ]
