# Generated by Django 5.2.5 on 2025-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description6',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='description7',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage1',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage2',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage3',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage4',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage5',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage6',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='stage7',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time4',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time5',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time6',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='time7',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material',
        ),
        migrations.RemoveField(
            model_name='material',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant1',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant2',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant3',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant4',
        ),
        migrations.RemoveField(
            model_name='material',
            name='variant5',
        ),
        migrations.AddField(
            model_name='detail',
            name='descriptions',
            field=models.TextField(default=';;;;;;'),
        ),
        migrations.AddField(
            model_name='detail',
            name='stages',
            field=models.TextField(default=';;;;;;'),
        ),
        migrations.AddField(
            model_name='detail',
            name='times',
            field=models.TextField(default=';;;;;;'),
        ),
        migrations.AddField(
            model_name='material',
            name='plate_lenght',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='plate_width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='slash_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='sort',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='square_m_weidth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='cdw_file_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='cdw_file_folder',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='cdw_file_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='cdw_valid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='frw_file_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='frw_file_folder',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='frw_file_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='frw_file_parts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='frw_valid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='grave',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='marshrut',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='material_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='poddon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sb',
            name='cdw_file_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sb',
            name='cdw_file_folder',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sb',
            name='cdw_file_name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sb',
            name='cdw_valid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sb',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sb',
            name='composition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sb',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sb',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
