# Generated by Django 5.2.5 on 2025-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsBase', '0002_remove_detail_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='original',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
