# Generated by Django 5.2.5 on 2025-09-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsBase', '0003_material_color_material_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sb',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='detail',
            name='material_name',
        ),
        migrations.AddField(
            model_name='detail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DetailsBase.material'),
        ),
    ]
